### ISSUE TITLE
[dev] Port to 1.20.5 - 1.20.6

### ISSUE THREAD

**Issue by lonefelidae16** [lonefelidae16/extra-sounds#15]
Ported code is available from ~[draft/port/1.20.5 branch](https://github.com/lonefelidae16/extra-sounds/tree/draft/port/1.20.5)~.
Removed.

~Snapshot version will be released when the [ARRP](https://github.com/Devan-Kerman/ARRP) project is ported to 1.20.5 or later due to [MPL license restrictions](https://www.mozilla.org/en-US/MPL/2.0/); **3.2. Distribution of Executable Form** - modded code must be published if bundling the compiled JARs.~

I decided to code some of the features of the ARRP.

As always, stable version will be released upon completion of the following checklist:

- [x] Port of ARRP functions
- [x] Open Music &amp; Sound Options screen
- [x] Change the default volume
- [x] Re-launch and obtain saved volume
- [x] All in-game features work fine
  - [x] Survival/Creative inventory sounds
  - [x] Hotbar sounds
  - [x] Item Interaction sound
  - [x] Block Interaction sound
  - [x] Chat sounds
  - [x] Keyboard sounds
  - [x] Give/Remove Effect sounds
- [x] Does this have compatibility with other MC versions?
  - [x] 1.20.5
- [x] Verify integrations
  - [x] [RoughlyEnoughItems](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items)

My stomach hurts, I think I ate too many poisonous potatoes...
Happy spring ;)

**Comment by lonefelidae16** [comment]
published but actually playing for debug now...

https://artifactory.kow08absty.com/artifactory/fabricmc/dev/stashy/extra-sounds/2.3.1%2B1.20.6%7Elonefelidae16-build.1/extra-sounds-2.3.1%2B1.20.6%7Elonefelidae16-build.1.jar

**Comment by lonefelidae16** [comment]
Looks good for now.

**Comment by DeshiDesu** [comment]
based dev
