### ISSUE TITLE
Artifactory links are down

### ISSUE THREAD

**Issue by han5enar** [lonefelidae16/extra-sounds#16]
### Environment info

Microsoft Edge

### Description

The links that you provided for download are showing a 503 error message page with "service unavailable".

### Step-by-step reproduction instructions

1. Click on the link "https://artifactory.kow08absty.com/artifactory/fabricmc/dev/stashy/extra-sounds/2.3.1%2B1.20.4~lonefelidae16-build.3/extra-sounds-2.3.1%2B1.20.4~lonefelidae16-build.3.jar"

### Screenshots, latest.log, code snippet

![image](https://github.com/lonefelidae16/extra-sounds/assets/155386429/e0927be0-61c5-419b-9109-57d020565090)

**Comment by lonefelidae16** [comment]
Thanks for your report. I was late to notice because Artifactory has been
stable for a very long time.

From the logs, it looks like the core process disappeared at the end of
April. What happened at this time?

I've put in place a script to restart it periodically. Thank you for your
patience.

**Comment by han5enar** [comment]
Yeah i just barely noticed this today so thanks for putting it back up again
