### ISSUE TITLE
1.19.4 support

### ISSUE THREAD

**Issue by Vi-Tul** [lonefelidae16/extra-sounds#2]
Was using this port on 1.19.3, now i'm moving to 1.19.4. Is it possible to run it on this version?
Btw, great work!

**Comment by lonefelidae16** [comment]
1.19.3 port is incompatible with 1.19.4, but 1.19.4 port is available. Please check newer version of [GitHub tags](https://github.com/lonefelidae16/extra-sounds/tags).

**Comment by Vi-Tul** [comment]
Thanks for the quick reply, will try!
