### ISSUE TITLE
typing sound?

### ISSUE THREAD

**Issue by pleepish** [lonefelidae16/extra-sounds#3]
i thought i remembered there being a config file for extra sounds where i could turn typing sounds on, but i don't see an option to configurate your version.

**Comment by lonefelidae16** [comment]
Thank you for your feedback. ExtraSounds’ configs are included in `options.txt` which is Minecraft’s options file. You can either edit this file directly or change the slider values in custom settings screen.

1. Open “Music & Sound Options” settings from game ptions.
1. Click on the gear button to the right of the “ExtraSounds” slider.
1. You can find “Typing” slider in this screen.

Currently, typing sound is off by default, so I’m thinking of making it sound during the porting to 1.20.

**Comment by lonefelidae16** [comment]
This suggestion is included in commit https://github.com/lonefelidae16/extra-sounds/commit/bb745fa683a537cf2dca2b03acf185692df579fe .
