### ISSUE TITLE
[Feature request] update to 1.20.1 

### ISSUE THREAD

**Issue by Rozbiynk** [lonefelidae16/extra-sounds#5]
yes

**Comment by lonefelidae16** [comment]
Oh, sorry, for 1.20 works well on 1.20.1 and I thought it doesn’t need to version bump. Have you had any crashes or some features not working? Please check and comment again when you find any problems.

**Comment by Rozbiynk** [comment]
oh, yea, sorry, i thought if it have 1.20 in gradle properties it doesnt launch on 1.20.1, everything is normal
