### ISSUE TITLE
REI Integration

### ISSUE THREAD

**Issue by DaCooladeMan** [lonefelidae16/extra-sounds#8]
I am unsure if the Official Extra Sounds mod is integrated with REI, so I don't know whether to post this here or not, but either way... Please add integration to the REI mod. When you search in the bar of REI, it doesn't make the typing sound. The Mod is integrated with Mod Menu, so I don't know why it doesn't work with REI.

**Comment by lonefelidae16** [comment]
This feature is implemented in commit 2d061655e03f371bd57942e385424c88b3968ead and d2c7a862cab4a82be337a3454e2dab356247b364 , and will be ported and released in 1.20.2.

Artifacts are also available from GitHub Actions if you want: https://github.com/lonefelidae16/extra-sounds/actions/runs/5917678834

**Comment by lonefelidae16** [comment]
update: With commit 835bd92ac3c5c4db093f126839f035cc1c635302 , fixed crash when launched without REI. Patched artifact is here: https://github.com/lonefelidae16/extra-sounds/actions/runs/5917743329

**Comment by lonefelidae16** [comment]
Sorry, I don’t have much time to devote to debugging for this.

I’ve played about 6 hours with or without REI and haven’t seen no more bugs or crashes, but if you have any concerns, please feel free to comment. Any trivial details are welcome.

**Comment by DaCooladeMan** [comment]
> Sorry, I don’t have much time to devote to debugging for this.
> 
> I’ve played about 6 hours with or without REI and haven’t seen no more bugs or crashes, but if you have any concerns, please feel free to comment. Any trivial details are welcome.

Thanks for all of your hard work! I'll definitely check it out.

**Comment by lonefelidae16** [comment]
RoughlyEnoughItems doesn’t seem to be officially compatible with release version 1.20.2 yet, but I tried it here and it works fine with 13.0.655. How’s this?

**Comment by DaCooladeMan** [comment]
> RoughlyEnoughItems doesn’t seem to be officially compatible with release version 1.20.2 yet, but I tried it here and it works fine with 13.0.655. How’s this?

Sorry for taking me so long to reply, it's good. I mostly play on 1.20.1 because I play Modded.

But I tried it out, it's been cool!

**Comment by lonefelidae16** [comment]
Oh, thanks for trying! And sorry about that.

I suspect a frightening amount of issues will be created, because Minecraft has so many versions. Like “Port to 1.19.x?”, “1.18.2 pls”. Recently I’ve seen some issues in other repositories asking for a port to 1.12.
I’m very reluctant to discuss porting to past versions.

Anyway, thank you so much! I’ll continue to support this integration.

**Comment by lonefelidae16** [comment]
Closing with commit 2d061655e03f371bd57942e385424c88b3968ead, d2c7a862cab4a82be337a3454e2dab356247b364 and 835bd92ac3c5c4db093f126839f035cc1c635302.
