### ISSUE TITLE
port to 1.20.1

### ISSUE THREAD

**Issue by brinys** [lonefelidae16/extra-sounds#9]
**Describe your suggestion**

**Additional context**

**Comment by lonefelidae16** [comment]
Compatibility with 1.20.2 already exists. I wont support backporting and will mark 1.20.1 as discontinued. Please check [GitHub tags](https://github.com/lonefelidae16/extra-sounds/tags) and expand each tag to get the link.

**Comment by lonefelidae16** [comment]
update: This fork has been bumped to v3 and now supports multiple versions, including 1.20.1. Please check [GitHub tags](https://github.com/lonefelidae16/extra-sounds/tags).

**Comment by lonefelidae16** [comment]
Closing with commit a6f4f6600482813a88903bbcbf6e9aadf408ec7f
